#!/usr/bin/env python3
"""Inject relevant phronix memory and standing rules at prompt submission.

Generated by phronix.hooks — edit hooks.py and run `phronix sync hooks` to
re-render. Do not edit this file directly; the next sync overwrites it.

A thin shim: Claude Code and Codex CLI both hand a JSON payload on stdin and add
whatever we print to the model's context. The real logic lives in
phronix.hook_entry so the harnesses cannot drift apart.

Never fails the turn — any error exits 0 silently.
"""
import sys

try:
    from phronix.hook_entry import run
except Exception:
    sys.exit(0)

try:
    block = run(sys.stdin.read())
except Exception:
    sys.exit(0)

if block:
    sys.stdout.write(block + "\n")
sys.exit(0)
