"""Render the prompt-injection hook for every harness that supports one.

The MCP middleware (``context_middleware``) already covers *tool* traffic for
all four harnesses, because they all talk to the same server. What it cannot
see is the user's raw prompt — that never reaches MCP. Hooks close exactly that
gap, so this module is deliberately narrow: one script, one event per harness.

Per-harness reality, which is why this is not uniform:

* **claude** — ``.claude/settings.json`` ``hooks.UserPromptSubmit``. A hook that
  prints to stdout has that text added to the model's context.
* **codex** — ``.codex/hooks.json`` ``UserPromptSubmit``, same shape and payload
  as Claude's. Requires the user to opt in with ``[features].codex_hooks = true``
  in their OWN ``~/.codex/config.toml``; a repo cannot enable it for them, so
  ``sync_hooks`` reports that as an advisory rather than writing there.
* **opencode** — no command hooks; it has a TypeScript *plugin* API instead.
  ``chat.message`` is the prompt-level equivalent. Plugins mutate ``output``
  (return values are discarded) and unknown hook keys are silently ignored.
* **copilot** — no path-scoped hook mechanism at all. Tool traffic is still
  covered by the middleware; prompt-level injection falls back to the
  instructions file.

The hook script itself is harness-neutral: it reads the JSON hook payload on
stdin, pulls ``prompt``, and prints the context block. The same file backs both
Claude and Codex.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict, Optional

from dftracer_agents.bootstrap import bundled_workspace_dir

HOOK_SCRIPT_NAME = "inject_context.py"
OPENCODE_PLUGIN_NAME = "dftracer-context.js"

# ---------------------------------------------------------------------------
# The shared hook script (claude + codex)
# ---------------------------------------------------------------------------

_HOOK_SCRIPT = '''#!/usr/bin/env python3
"""Inject relevant dftracer memory + standing rules at prompt submission.

Generated by dftracer_agents.hooks — edit hooks.py, then run
`dftracer-sync-hooks` to re-render. Do not edit this file directly.

A thin shim: Claude Code and Codex CLI both hand a JSON payload on stdin and
add whatever we print to the model's context. All the real logic lives in
dftracer_agents.hook_entry so the three harnesses cannot drift apart.

Never fails the turn — any error exits 0 silently.
"""
import sys

try:
    from dftracer_agents.hook_entry import run
except Exception:
    sys.exit(0)

try:
    block = run(sys.stdin.read())
except Exception:
    sys.exit(0)

if block:
    sys.stdout.write(block + "\\n")
sys.exit(0)
'''

# ---------------------------------------------------------------------------
# The opencode plugin (TypeScript/JS)
# ---------------------------------------------------------------------------
#
# opencode plugins mutate `output`; returned values are discarded. `chat.message`
# is the prompt-level event. We shell out to the same Python entry point the
# command-hook harnesses use so there is exactly one implementation of the
# retrieval logic.

_OPENCODE_PLUGIN = '''// Generated by dftracer_agents.hooks — edit hooks.py and re-run
// `dftracer-sync-hooks`; do not edit this file directly.
//
// opencode has no command hooks, so prompt-level memory injection goes through
// the plugin API. `chat.message` fires on each user message; hooks mutate the
// `output` object (return values are discarded) and unknown hook keys are
// silently ignored, so the key name below must match the API exactly.
//
// Tool-call context is NOT injected here — the dftracer MCP server's own
// middleware already does that for every harness uniformly.

import { spawn } from "child_process"

function inject(prompt, sessionID) {
  return new Promise((resolve) => {
    let out = ""
    let done = false
    const finish = () => { if (!done) { done = true; resolve(out.trim()) } }
    try {
      const proc = spawn("python3", ["-m", "dftracer_agents.hook_entry"], {
        stdio: ["pipe", "pipe", "ignore"],
      })
      // Never hang a user's turn on memory lookup.
      const timer = setTimeout(() => { try { proc.kill() } catch (e) {} finish() }, 5000)
      proc.stdout.on("data", (d) => { out += d.toString() })
      proc.on("error", () => { clearTimeout(timer); finish() })
      proc.on("close", () => { clearTimeout(timer); finish() })
      proc.stdin.write(JSON.stringify({ prompt, session_id: sessionID }))
      proc.stdin.end()
    } catch (e) {
      finish()
    }
  })
}

export const DftracerContext = async ({ project, client, $, directory }) => ({
  "chat.message": async (input, output) => {
    try {
      const parts = output?.message?.parts
      if (!Array.isArray(parts)) return
      const textPart = parts.find((p) => p?.type === "text" && typeof p.text === "string")
      if (!textPart || !textPart.text.trim()) return
      const block = await inject(textPart.text, output?.message?.sessionID || "opencode")
      if (block) textPart.text = `${textPart.text}\\n\\n${block}`
    } catch (e) {
      // Injection is an enhancement; never break the turn.
    }
  },
})
'''


def hook_script_source() -> str:
    return _HOOK_SCRIPT


def opencode_plugin_source() -> str:
    return _OPENCODE_PLUGIN


def _write_if_changed(path: Path, content: str, executable: bool = False) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == content:
        return "already_current"
    path.write_text(content)
    if executable:
        path.chmod(0o755)
    return "updated"


# ---------------------------------------------------------------------------
# Installing the scripts where the harness actually resolves them
# ---------------------------------------------------------------------------
#
# A hook command is a RELATIVE path (".claude/hooks/inject_context.py") resolved
# against the project root the harness runs in — not against this package. The
# packaged workspace is only the source of truth; bootstrap normally symlinks
# `.claude/hooks` out to a target root, but when that directory already exists as
# a REAL directory (as it does in this repo, which has a hand-written
# guard_rm_drm.sh) the symlink is refused and the script never arrives.
#
# Writing a settings entry that points at a missing script breaks every prompt,
# so scripts are installed first and the settings entry is written only after the
# file is confirmed present.

def install_hook_scripts(target_root: Path) -> Dict[str, str]:
    """Materialise the hook scripts under *target_root*.

    Idempotent, and a no-op for any directory already symlinked to the packaged
    workspace (the content is reachable through the link).
    """
    target_root = Path(target_root)
    out: Dict[str, str] = {}
    for relative, content, executable in (
        (Path(".claude") / "hooks" / HOOK_SCRIPT_NAME, _HOOK_SCRIPT, True),
        (Path(".codex") / "hooks" / HOOK_SCRIPT_NAME, _HOOK_SCRIPT, True),
        (Path(".opencode") / "plugin" / OPENCODE_PLUGIN_NAME, _OPENCODE_PLUGIN, False),
    ):
        dest = target_root / relative
        try:
            out[str(relative)] = _write_if_changed(dest, content, executable=executable)
        except OSError as exc:
            out[str(relative)] = f"error: {exc}"
    return out


def hook_script_installed(root: Path, harness: str = "claude") -> bool:
    """True when the hook script exists where *harness* will look for it."""
    sub = ".claude" if harness == "claude" else ".codex"
    return (Path(root) / sub / "hooks" / HOOK_SCRIPT_NAME).is_file()


# ---------------------------------------------------------------------------
# Claude Code — .claude/settings.json
# ---------------------------------------------------------------------------

def render_claude_hook() -> Dict[str, Any]:
    return {
        "matcher": "",
        "hooks": [{
            "type": "command",
            "command": f"python3 .claude/hooks/{HOOK_SCRIPT_NAME}",
            "statusMessage": "Loading relevant project memory...",
            "timeout": 15,
        }],
    }


def sync_claude_hooks(base: Optional[Path] = None) -> str:
    """Merge the UserPromptSubmit hook into settings.json, preserving others.

    Additive on purpose: this file already carries a hand-written ``PreToolUse``
    rm/drm guard, and replacing ``hooks`` wholesale would delete it.
    """
    root = base or bundled_workspace_dir()
    # The script and the settings entry are two separate artifacts; a change to
    # either counts as "updated" or a script-only edit would be reported as
    # already-current and look like a no-op.
    script_status = _write_if_changed(
        root / ".claude" / "hooks" / HOOK_SCRIPT_NAME, _HOOK_SCRIPT, executable=True)

    # Never advertise a hook whose script is not on disk: Claude Code runs the
    # command on EVERY prompt, so a dangling path fails every turn.
    if not hook_script_installed(root, "claude"):
        return "skipped_missing_script"

    path = root / ".claude" / "settings.json"
    data: Dict[str, Any] = json.loads(path.read_text()) if path.exists() else {}
    hooks = data.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        return "skipped_unexpected_shape"

    entry = render_claude_hook()
    existing = hooks.get("UserPromptSubmit")
    ours = [e for e in (existing or []) if _is_ours(e)]
    others = [e for e in (existing or []) if not _is_ours(e)]
    if ours == [entry] and existing == others + ours:
        return script_status
    hooks["UserPromptSubmit"] = others + [entry]
    path.write_text(json.dumps(data, indent=2) + "\n")
    return "updated"


def _is_ours(entry: Any) -> bool:
    """True for hook entries this module generated (match on the script name)."""
    if not isinstance(entry, dict):
        return False
    return any(
        HOOK_SCRIPT_NAME in str(h.get("command", ""))
        for h in entry.get("hooks", []) if isinstance(h, dict)
    )


# ---------------------------------------------------------------------------
# Codex CLI — .codex/hooks.json
# ---------------------------------------------------------------------------

def sync_codex_hooks(base: Optional[Path] = None) -> str:
    """Write .codex/hooks.json with the same UserPromptSubmit hook.

    Codex reads hooks from a dedicated file rather than its config.toml. The
    engine is opt-in per user (``[features].codex_hooks = true`` in
    ``~/.codex/config.toml``) and a repo must not write there — see
    ``advisories()``.
    """
    root = base or bundled_workspace_dir()
    _write_if_changed(root / ".codex" / "hooks" / HOOK_SCRIPT_NAME,
                      _HOOK_SCRIPT, executable=True)

    payload = {
        "hooks": {
            "UserPromptSubmit": [{
                "matcher": "",
                "hooks": [{
                    "type": "command",
                    "command": f"python3 .codex/hooks/{HOOK_SCRIPT_NAME}",
                    "statusMessage": "Loading relevant project memory...",
                    "timeout": 15,
                }],
            }],
        },
    }
    return _write_if_changed(root / ".codex" / "hooks.json",
                             json.dumps(payload, indent=2) + "\n")


# ---------------------------------------------------------------------------
# OpenCode — .opencode/plugin/*.js
# ---------------------------------------------------------------------------

def sync_opencode_plugin(base: Optional[Path] = None) -> str:
    root = base or bundled_workspace_dir()
    return _write_if_changed(
        root / ".opencode" / "plugin" / OPENCODE_PLUGIN_NAME, _OPENCODE_PLUGIN)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def advisories() -> Dict[str, str]:
    """Things the user must do themselves; a repo cannot do them safely."""
    return {
        "codex": ("Codex hooks are opt-in: add `[features]\\ncodex_hooks = true` to "
                  "~/.codex/config.toml. A repo must not write to your global config."),
        "copilot": ("Copilot exposes no hook mechanism; prompt-level memory relies on "
                    "copilot-instructions.md. Tool calls are still covered by the MCP "
                    "middleware."),
    }


def sync_hooks(base: Optional[Path] = None) -> Dict[str, Any]:
    results = {
        "claude": sync_claude_hooks(base),
        "codex": sync_codex_hooks(base),
        "opencode": sync_opencode_plugin(base),
        "copilot": "not_applicable",
    }
    changed = [h for h, s in results.items() if s == "updated"]
    return {
        **results,
        "changed": changed,
        "advisories": advisories(),
        "summary": (f"{len(changed)} harness hook(s) updated" if changed
                    else "all harness hooks already current"),
    }


def ensure_hooks_setup(target_root: Optional[Path] = None, force: bool = False) -> Dict[str, Any]:
    """Startup-loop signature, matching skills/agents/permissions setup steps.

    Unlike the permissions step, this must ALSO write into ``target_root``.
    Hook commands are relative paths resolved against the project the harness
    runs in, and a project whose ``.claude/hooks`` is a real directory (rather
    than a symlink to the packaged workspace) never receives the script from
    bootstrap. Skipping that install is what left every prompt calling a
    nonexistent file.
    """
    result = sync_hooks()

    installed: Dict[str, str] = {}
    if target_root is not None:
        root = Path(target_root).expanduser().resolve()
        if root != bundled_workspace_dir().resolve():
            installed = install_hook_scripts(root)
    result["target_scripts"] = installed

    changed = bool(result["changed"]) or any(
        s == "updated" for s in installed.values())
    return {
        "status": "installed" if changed or force else "already_done",
        "target": str(target_root or bundled_workspace_dir()),
        **result,
    }


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        prog="dftracer-sync-hooks",
        description="Render the prompt-injection hooks for every harness that supports one.",
    )
    parser.parse_args()
    result = sync_hooks()
    for harness in ("claude", "codex", "opencode", "copilot"):
        print(f"{harness:9s} {result[harness]}")
    print(result["summary"])
    for harness, note in result["advisories"].items():
        print(f"\nNOTE ({harness}): {note}")


if __name__ == "__main__":
    main()
