"""Runtime helper sources dropped into an app's source tree for provenance mode.

These are embedded as string constants (not package-data files) so they ship with
the wheel without touching ``pyproject.toml``. ``provenance_install_helpers``
writes them into the session's provenance source tree.

Event model (identical in every language, so a C producer and a Python consumer
join on the same entity hash):

* **Entity** -- a unique instance of an entity *type* (e.g. ``protein_structure``
  / ``1abc_model_3``).  Its identity is ``hash = FNV-1a-64(type + "\\x1f" + id)``
  printed as 16 lowercase hex digits.  The first time a process touches an
  entity it emits ONE dftracer metadata event::

      key   = "prov_entity:<hash>"
      value = "<type>|<id>|<store>|<uri>"

* **Activity** -- a normal dftracer data event (category ``PROV``) spanning the
  transformation, carrying the cause/effect edges as event args::

      prov_aid       unique activity instance id "<pid>-<seq>"
      prov_activity  activity type (e.g. "fold", "write_checkpoint")
      prov_used      comma-separated entity hashes consumed  (cause)
      prov_generated comma-separated entity hashes produced  (effect)
      prov_nused / prov_ngen   counts (detects truncation)

  Lists longer than ``DFT_PROV_CHUNK`` bytes spill into extra ``PROV_CONT``
  events with the same ``prov_aid``; the graph builder merges them.

* **Entity type description** -- what a type represents in the workflow, from
  the spec. Emitted once per process per type as a metadata record::

      key   = "prov_type:<type>"
      value = "<role>|<description>"     role = input | output | intermediate

  The helpers emit the generated registry (``dftracer_prov_types.py`` /
  ``dftracer_prov_types.h``, written by ``provenance_install_helpers`` from the
  spec) automatically the first time a process declares an entity, so every
  trace that holds entities also explains their types.

Args on data events are only serialized when ``DFTRACER_INC_METADATA=1``.
dftracer splices values into JSON unescaped, so ids are sanitized for display
(``"``, ``\\``, ``|``, control chars -> ``_``) -- the hash is over the RAW id.
"""

PROV_C_HEADER = r'''/* dftracer_prov.h -- provenance helpers over the dftracer entity/relation API
 * (generated by provenance_install_helpers; regenerate, do not hand-edit).
 *
 * C and C++. Ids, hashing, sanitizing and records are done by the dftracer
 * core (dftracer.h / core/common/entity.h); this header only gives
 * provenance-shaped names:
 *
 *   DFT_PROV_ACTIVITY(act, "write_checkpoint", "checkpoint");  // scoped region
 *   dft_prov_used(&act, "mesh_state", key, DFT_STORE_MEMORY, NULL);
 *   EntityID out = dft_prov_generated(&act, "checkpoint_file", path,
 *                                     DFT_STORE_PARALLEL_FS, path);
 *   dft_prov_relate(DFT_REL_DERIVED_FROM, out, in);             // entity->entity
 */
#ifndef DFTRACER_PROV_H
#define DFTRACER_PROV_H

#include <dftracer/dftracer.h>

#define DFT_PROV_CAT "PROV"

typedef struct dft_prov_activity {
  struct DFTracerData* data;
} dft_prov_activity_t;

static inline void dft_prov_begin(dft_prov_activity_t* a, const char* name,
                                  const char* type) {
  a->data = initialize_region(name, DFT_PROV_CAT, DF_DATA_EVENT);
  if (type) update_metadata_string(a->data, "activity", type);
}
static inline void dft_prov_end(dft_prov_activity_t* a) {
  if (a->data) {
    finalize_region(a->data);
    a->data = NULL;
  }
}
static inline void dft_prov__cleanup(dft_prov_activity_t* a) { dft_prov_end(a); }

static inline void dft_prov__auto_types(void);

static inline EntityID dft_prov_relate_event(dft_prov_activity_t* a,
                                             EntityRelation rel,
                                             ConstEntityTypeName type,
                                             ConstEntityKey key,
                                             EntityStore store,
                                             ConstEntityURI uri) {
  dft_prov__auto_types();
  return update_relation_entity(a->data, rel, type, key, store, uri);
}
#define dft_prov_used(a, type, key, store, uri) \
  dft_prov_relate_event(a, DFT_REL_USED, type, key, store, uri)
#define dft_prov_generated(a, type, key, store, uri) \
  dft_prov_relate_event(a, DFT_REL_GENERATED, type, key, store, uri)
#define dft_prov_invalidated(a, type, key, store, uri) \
  dft_prov_relate_event(a, DFT_REL_INVALIDATED, type, key, store, uri)
#define dft_prov_updated(a, type, key, store, uri) \
  dft_prov_relate_event(a, DFT_REL_UPDATED, type, key, store, uri)
#define dft_prov_entity(type, key, store, uri) \
  (dft_prov__auto_types(), dftracer_declare_entity(type, key, store, uri))
#define dft_prov_relate(rel, subject, object) \
  dftracer_relate_entities(rel, subject, object)
#define dft_prov_describe(type, role, description) \
  dftracer_declare_entity_type(type, role, description)

/* Scoped activity: ends when `var` leaves scope (gcc/clang cleanup attr). */
#if defined(__GNUC__) || defined(__clang__)
#define DFT_PROV_ACTIVITY(var, name, type)                                  \
  dft_prov_activity_t var __attribute__((cleanup(dft_prov__cleanup)));     \
  dft_prov_begin(&var, name, type)
#else
#define DFT_PROV_ACTIVITY(var, name, type) \
  dft_prov_activity_t var;                 \
  dft_prov_begin(&var, name, type)
#endif

/* Generated from the spec by provenance_install_helpers, when present. */
#if defined(__has_include)
#if __has_include("dftracer_prov_types.h")
#include "dftracer_prov_types.h"
#define DFT_PROV_HAVE_TYPES 1
#endif
#endif
static int dft_prov__types_done = 0;
static inline void dft_prov__auto_types(void) {
#ifdef DFT_PROV_HAVE_TYPES
  if (!dft_prov__types_done) {
    dft_prov__types_done = 1;
    dft_prov_register_types();
  }
#endif
}

#ifdef __cplusplus
namespace dftprov {
/* RAII activity for C++. */
class Activity {
  dft_prov_activity_t a_;

 public:
  Activity(const char* name, const char* type = nullptr) {
    dft_prov_begin(&a_, name, type);
  }
  Activity(const Activity&) = delete;
  Activity& operator=(const Activity&) = delete;
  ~Activity() { dft_prov_end(&a_); }
  EntityID used(ConstEntityTypeName t, ConstEntityKey k,
                EntityStore s = DFT_STORE_MEMORY, ConstEntityURI u = nullptr) {
    return dft_prov_used(&a_, t, k, s, u);
  }
  EntityID generated(ConstEntityTypeName t, ConstEntityKey k,
                     EntityStore s = DFT_STORE_MEMORY,
                     ConstEntityURI u = nullptr) {
    return dft_prov_generated(&a_, t, k, s, u);
  }
  EntityID invalidated(ConstEntityTypeName t, ConstEntityKey k,
                       EntityStore s = DFT_STORE_MEMORY,
                       ConstEntityURI u = nullptr) {
    return dft_prov_invalidated(&a_, t, k, s, u);
  }
  void end() { dft_prov_end(&a_); }
};
}  // namespace dftprov
#endif /* __cplusplus */

#endif /* DFTRACER_PROV_H */
'''

PROV_PY_MODULE = r'''"""dftracer_prov -- provenance helpers over the dftracer entity/relation API
(generated by provenance_install_helpers; regenerate rather than hand-edit).

    import dftracer_prov as prov
    with prov.activity("fold_structure", "fold") as act:
        act.used("sequence", seq_id)
        act.generated("protein_structure", out_path, prov.Store.PARALLEL_FS, out_path)
    prov.relate(prov.Relation.CONTAINS, tar_id, member_id)    # entity -> entity

Ids, types, stores, roles and relations are handled by the dftracer core
(64-bit EntityID from (type, key); EH/ET/ER records; relation arrays on the
event). `store` takes a prov.Store enum, or a legacy string ("memory",
"file", "db", "object", "network", "gpu"); "file" is resolved from the uri's
path (Rabbit /mnt/nnf -> BURST_BUFFER, Lustre/VAST/GPFS -> PARALLEL_FS,
/tmp, /dev/shm, /var/tmp -> LOCAL_DISK). Everything is a cheap no-op when
dftracer, or its entity API, is unavailable or DFTRACER_ENABLE=0.
"""
import os
import threading

try:  # pragma: no cover - exercised at app runtime
    from dftracer.python import (
        dft_fn as _dft_fn,
        dftracer as _dft,
        EntityRelation as Relation,
        EntityRole as Role,
        EntityStore as Store,
    )
    _ENABLED = os.environ.get("DFTRACER_ENABLE", "1") != "0"
except Exception:  # dftracer missing or pre-entity-API -> no-op
    from enum import IntEnum

    class Store(IntEnum):  # mirrors dftracer core/common/entity.h
        MEMORY = 0; GPU_MEMORY = 1; LOCAL_DISK = 2; PARALLEL_FS = 3
        BURST_BUFFER = 4; OBJECT_STORE = 5; DATABASE = 6; NETWORK = 7; OTHER = 8

    class Role(IntEnum):
        UNKNOWN = 0; INPUT = 1; OUTPUT = 2; INTERMEDIATE = 3; PARAMETER = 4; REFERENCE = 5

    class Relation(IntEnum):
        USED = 0; GENERATED = 1; INVALIDATED = 2; UPDATED = 3
        DERIVED_FROM = 16; REVISION_OF = 17; CONTAINS = 18; PART_OF = 19
        SPECIALIZATION_OF = 20; ALTERNATE_OF = 21; DEPENDS_ON = 22

    _dft = _dft_fn = None
    _ENABLED = False

CAT = "PROV"
_LEGACY_STORE = {"memory": Store.MEMORY, "gpu": Store.GPU_MEMORY,
                 "db": Store.DATABASE, "database": Store.DATABASE,
                 "object": Store.OBJECT_STORE, "network": Store.NETWORK,
                 "other": Store.OTHER}
_PFS = ("/p/lustre", "/p/vast", "/p/gpfs", "/lustre", "/gpfs")
_LOCAL = ("/tmp", "/dev/shm", "/var/tmp", "/l/ssd")


def file_store(uri):
    """EntityStore for a file path (where it physically lives)."""
    u = str(uri or "")
    if u.startswith("/mnt/nnf/"):
        return Store.BURST_BUFFER
    if u.startswith(_LOCAL):
        return Store.LOCAL_DISK
    return Store.PARALLEL_FS if u.startswith(_PFS) or u.startswith("/") else Store.OTHER


def _store(store, uri):
    if isinstance(store, int):
        return Store(int(store))
    s = str(store or "memory").lower()
    if s == "file":
        # a "file" with no path (e.g. a built-in preset standing in for a
        # config file) lives in memory
        return file_store(uri) if uri else Store.MEMORY
    return _LEGACY_STORE.get(s, Store.OTHER)


_lock = threading.Lock()
_types_done = set()  # pids that emitted the type registry


def _log():
    return _dft.get_instance() if _ENABLED else None


def entity(etype, key, store="memory", uri=""):
    """Declare an entity instance; return its EntityID (0 when tracing is off)."""
    lg = _log()
    if lg is None:
        return 0
    _auto_types()
    return lg.declare_entity(etype, str(key), _store(store, uri), str(uri or ""))


def describe(etype, description, role=Role.UNKNOWN):
    """Describe an entity type once per process (role, description)."""
    lg = _log()
    if lg is None:
        return
    if not isinstance(role, int):
        role = getattr(Role, str(role).upper(), Role.UNKNOWN)
    lg.declare_entity_type(etype, Role(int(role)), description or "")


def relate(relation, subject, object_):
    """Entity -> entity relation (Relation.CONTAINS, DERIVED_FROM, ...)."""
    lg = _log()
    if lg is not None and subject and object_:
        lg.relate_entities(Relation(int(relation)), subject, object_)


def _auto_types():
    """Emit the generated type registry (dftracer_prov_types) once per process."""
    pid = os.getpid()
    with _lock:
        if pid in _types_done:
            return
        _types_done.add(pid)
    try:
        from dftracer_prov_types import TYPES
    except Exception:
        try:
            from .dftracer_prov_types import TYPES  # helper installed in a package
        except Exception:
            return
    for t, v in TYPES.items():
        role, desc = v if isinstance(v, tuple) else ("", v)
        describe(t, desc, role)


class activity:
    """One PROV event; its relations (used/generated/...) are written by the
    dftracer core as arrays of entity ids on the event."""

    def __init__(self, name, atype=None):
        self.name = name
        self.atype = atype or name
        self._ev = None

    def __enter__(self):
        if _ENABLED:
            self._ev = _dft_fn(CAT, name=self.name)
            self._ev.__enter__()
            self._ev.update(args={"activity": self.atype})
        return self

    def _rel(self, relation, etype, key, store, uri):
        if self._ev is None:
            return 0
        _auto_types()
        return self._ev.relate_entity(Relation(int(relation)), etype, str(key),
                                      _store(store, uri), str(uri or ""))

    def used(self, etype, key, store="memory", uri=""):
        return self._rel(Relation.USED, etype, key, store, uri)

    def generated(self, etype, key, store="memory", uri=""):
        return self._rel(Relation.GENERATED, etype, key, store, uri)

    def invalidated(self, etype, key, store="memory", uri=""):
        """The activity ended the entity (deleted, consumed, overwritten)."""
        return self._rel(Relation.INVALIDATED, etype, key, store, uri)

    def updated(self, etype, key, store="memory", uri=""):
        """The activity modified the entity in place."""
        return self._rel(Relation.UPDATED, etype, key, store, uri)

    def __exit__(self, exc_type, exc, tb):
        if self._ev is not None:
            self._ev.__exit__(exc_type, exc, tb)
            self._ev = None
        return False


def traced(name, atype=None):
    """Decorator form; inside the function use prov.current() to record."""
    import functools

    def deco(f):
        @functools.wraps(f)
        def w(*a, **k):
            with activity(name, atype) as act:
                _tls.stack = getattr(_tls, "stack", []) + [act]
                try:
                    return f(*a, **k)
                finally:
                    _tls.stack.pop()
        return w
    return deco


_tls = threading.local()


def current():
    """Innermost activity opened by @traced in this thread (or None)."""
    st = getattr(_tls, "stack", None)
    return st[-1] if st else None
'''
