// Generated by phronix.hooks — edit hooks.py and run `phronix sync hooks`.
// Do not edit this file directly; the next sync overwrites it.
//
// OpenCode has no command hooks, so prompt-level memory injection goes through
// the plugin API. `chat.message` fires on each user message; hooks mutate the
// `output` object (return values are discarded) and unknown hook keys are
// silently ignored, so the key name below must match the API exactly.
//
// Tool-call context is NOT injected here — the phronix MCP server's own
// middleware already covers that uniformly for every harness.

import { spawn } from "child_process"

function inject(prompt, sessionID) {
  return new Promise((resolve) => {
    let out = ""
    let done = false
    const finish = () => { if (!done) { done = true; resolve(out.trim()) } }
    try {
      const proc = spawn("python3", ["-m", "phronix.hook_entry"], {
        stdio: ["pipe", "pipe", "ignore"],
      })
      // Never hang a user's turn on a memory lookup.
      const timer = setTimeout(() => { try { proc.kill() } catch (e) {} finish() }, 5000)
      proc.stdout.on("data", (d) => { out += d.toString() })
      proc.on("error", () => { clearTimeout(timer); finish() })
      proc.on("close", () => { clearTimeout(timer); finish() })
      proc.stdin.write(JSON.stringify({ prompt, session_id: sessionID }))
      proc.stdin.end()
    } catch (e) {
      finish()
    }
  })
}

export const PhronixContext = async ({ project, client, $, directory }) => ({
  "chat.message": async (input, output) => {
    try {
      const parts = output?.message?.parts
      if (!Array.isArray(parts)) return
      const textPart = parts.find((p) => p?.type === "text" && typeof p.text === "string")
      if (!textPart || !textPart.text.trim()) return
      const block = await inject(textPart.text, output?.message?.sessionID || "opencode")
      if (block) textPart.text = `${textPart.text}\n\n${block}`
    } catch (e) {
      // Injection is an enhancement; never break the turn.
    }
  },
})
