#!/usr/bin/env python3
"""Inject relevant dftracer memory + standing rules at prompt submission.

Generated by dftracer_agents.hooks — edit hooks.py, then run
`dftracer-sync-hooks` to re-render. Do not edit this file directly.

A thin shim: Claude Code and Codex CLI both hand a JSON payload on stdin and
add whatever we print to the model's context. All the real logic lives in
dftracer_agents.hook_entry so the three harnesses cannot drift apart.

Never fails the turn — any error exits 0 silently.
"""
import sys

try:
    from dftracer_agents.hook_entry import run
except Exception:
    sys.exit(0)

try:
    block = run(sys.stdin.read())
except Exception:
    sys.exit(0)

if block:
    sys.stdout.write(block + "\n")
sys.exit(0)
